name: React CI/CD Pipeline with Nginx

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test React App
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build
        env:
          CI: ""

    deploy:
      name: Deploy to Nginx Server
      runs-on: self-hosted
      needs: build
      steps:
        - name: List files in the repository (for debugging)
          run: ls -R

        - name: Verify build directory exists
          run: |
            if [ ! -d "build" ]; then
              echo "Build directory does not exist!";
              exit 1;
            fi

        - name: Copy build to Nginx server
          run: |
            sudo cp -r build/* /var/www/html/
      
        - name: Verify files copied
          run: |
            if [ "$(ls -A /var/www/html/)" ]; then
              echo "Files copied successfully.";
            else
              echo "Failed to copy files.";
              exit 1;

        - name: Restart Nginx
          run: sudo systemctl restart nginx
