name: React CI/CD Pipeline with Nginx

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test React App
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create .env file
        run: |
          echo "VITE_SERVER_URL=http://api.zzunipark.com/BoomVim/anHour" >> .env
          echo "VITE_IMG_URL=http://158.180.66.65:5000/get_image" >> .env
          echo "VITE_AI_IMG_URL=http://158.180.66.65:5000/get_image_output" >> .env
          echo "VITE_PEOPLE_URL = http://158.180.66.65:5001/aggregate_status" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build
        env:
          CI: ""

      - name: run pwd
        run: pwd

      - name : run whoami
        run: whoami

      - name: Check dist directory
        run: ls -l dist/
        
      - name: Deploy to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/


      - name: Restart Nginx
        run: sudo systemctl restart nginx
